openapi: 3.0.0
info:
  title: Product Service API
  version: 1.0.0
  description: Product management API for contract testing with Specmatic

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /api/products:
    get:
      summary: Get all products
      operationId: getAllProducts
      tags:
        - Products
      responses:
        '200':
          description: List of all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                success:
                  value:
                    - id: 1
                      name: "Widget"
                      description: "A useful widget"
                      price: 19.99
                      inStock: true
                    - id: 2
                      name: "Gadget"
                      description: "A handy gadget"
                      price: 29.99
                      inStock: true

    post:
      summary: Create a new product
      operationId: createProduct
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProductRequest'
            example:
              name: "New Widget"
              description: "A brand new widget"
              price: 24.99
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: 3
                name: "New Widget"
                description: "A brand new widget"
                price: 24.99
                inStock: true
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/products/{id}:
    get:
      summary: Get product by ID
      operationId: getProductById
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: 1
                name: "Widget"
                description: "A useful widget"
                price: 19.99
                inStock: true
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                code: "NOT_FOUND"
                message: "Product with id 999 not found"

    put:
      summary: Update a product
      operationId: updateProduct
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
            format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProductRequest'
            example:
              name: "Updated Widget"
              description: "An improved widget"
              price: 22.99
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: 1
                name: "Updated Widget"
                description: "An improved widget"
                price: 22.99
                inStock: true
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a product
      operationId: deleteProduct
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: Product ID
          schema:
            type: integer
            format: int32
      responses:
        '204':
          description: Product deleted successfully
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
        - inStock
      properties:
        id:
          type: integer
          format: int32
          description: Product ID
        name:
          type: string
          description: Product name
          minLength: 1
          maxLength: 100
        description:
          type: string
          description: Product description
          nullable: true
        price:
          type: number
          format: double
          description: Product price
          minimum: 0
        inStock:
          type: boolean
          description: Whether product is in stock

    CreateProductRequest:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          nullable: true
        price:
          type: number
          format: double
          minimum: 0

    UpdateProductRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        description:
          type: string
          nullable: true
        price:
          type: number
          format: double
          minimum: 0

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error message
